In [1]:
import numpy as np
import torch

PYTORCH DATATYPES - TENSORS

In [2]:
torch.tensor(10)

tensor(10)

Scaler - Vector - Matrix - Tensor

In [3]:
torch.tensor([10,20])

tensor([10, 20])

In [4]:
scaler = torch.tensor(10)

In [5]:
scaler

tensor(10)

In [6]:
scaler.dtype

torch.int64

In [7]:
scaler + 5

tensor(15)

In [8]:
vector = torch.tensor([10,20,30])
vector

tensor([10, 20, 30])

In [9]:
vector.dtype

torch.int64

In [10]:
vector.dim()

1

In [11]:
numpy_int = np.int32(10)

In [12]:
numpy_int

np.int32(10)

In [13]:
new_scaler = torch.tensor(25, dtype=torch.int32)

In [14]:
new_scaler

tensor(25, dtype=torch.int32)

In [15]:
new_scaler.dtype

torch.int32

In [17]:
vector = torch.tensor([10,20,30], dtype=torch.float32)

In [20]:
matrix = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
vector

tensor([10., 20., 30.])

In [22]:
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [23]:
matrix.shape

torch.Size([3, 3])

In [24]:
vector + matrix

tensor([[11., 22., 33.],
        [14., 25., 36.],
        [17., 28., 39.]])

In [25]:
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [26]:
tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [27]:
tensor.shape

torch.Size([2, 3, 3])

In [28]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_32_tensor

tensor([3., 6., 9.])