In [12]:
import torch
import numpy as np

In [13]:
random_array = np.random.randn(3,5)

In [14]:
random_array

array([[-0.86085797, -0.63058834, -0.25596881,  1.35230058, -0.69430644],
       [-0.33264097, -2.13894144,  0.8693083 ,  0.16012555, -1.15107651],
       [-0.52747371, -0.58020947, -0.63789465,  1.3801951 , -0.87578338]])

In [15]:
type(random_array)

numpy.ndarray

In [16]:
random_matrix = torch.rand(size=(3,5))

In [17]:
random_matrix

tensor([[0.9165, 0.6868, 0.1486, 0.8857, 0.6942],
        [0.8754, 0.0955, 0.3863, 0.0676, 0.8514],
        [0.4711, 0.9877, 0.4909, 0.7846, 0.4762]])

In [18]:
type(random_matrix)

torch.Tensor

In [20]:
random_image_tensor = torch.rand(size=(224,224,3))

In [21]:
random_image_tensor

tensor([[[0.9571, 0.8704, 0.2372],
         [0.9343, 0.7186, 0.8098],
         [0.7540, 0.9391, 0.1331],
         ...,
         [0.2926, 0.3628, 0.4608],
         [0.3935, 0.6513, 0.2806],
         [0.4324, 0.6100, 0.3302]],

        [[0.0035, 0.3959, 0.2630],
         [0.1864, 0.8825, 0.2154],
         [0.2328, 0.6642, 0.0204],
         ...,
         [0.2273, 0.7449, 0.9243],
         [0.8568, 0.2026, 0.4646],
         [0.0103, 0.0200, 0.7827]],

        [[0.8244, 0.3125, 0.7743],
         [0.5256, 0.6552, 0.9867],
         [0.7800, 0.1137, 0.5646],
         ...,
         [0.7269, 0.3438, 0.8093],
         [0.4482, 0.8741, 0.4103],
         [0.4956, 0.9230, 0.6063]],

        ...,

        [[0.4040, 0.9920, 0.6869],
         [0.4079, 0.6323, 0.5767],
         [0.9961, 0.0211, 0.2954],
         ...,
         [0.9987, 0.6128, 0.5610],
         [0.2935, 0.2469, 0.1424],
         [0.9510, 0.9682, 0.2249]],

        [[0.1090, 0.1226, 0.4419],
         [0.4073, 0.4884, 0.4658],
         [0.

In [22]:
vector_with_arange = torch.arange(start=0, end=10, step=1)

In [23]:
vector_with_arange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])