In [1]:
import torch
import numpy as np

In [2]:
tensor = torch.tensor([1,2,3])

In [3]:
tensor * tensor

tensor([1, 4, 9])

In [8]:
matrix = torch.tensor([[1,2,3],
                      [4,5,6],
                      [7,8,9]]
)

In [9]:
matrix * matrix

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [10]:
matrix @ matrix

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [11]:
A = torch.tensor([[1,2,3]])

In [12]:
A.shape

torch.Size([1, 3])

In [13]:
A.ndim

2

In [14]:
B = torch.tensor([[4], [5], [6]])

In [15]:
B.ndim

2

In [16]:
A @ B

tensor([[32]])

Manipulating Tensor: Reshaping, Stacking, Squeezing, Unsqueezing

In [17]:
x = torch.arange(1,10,1)

In [18]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x.shape

torch.Size([9])

In [20]:
x_reshaped = x.reshape(1,9)

In [25]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [26]:
x_reshaped.ndim

2

In [27]:
x_reshaped = x.reshape(3,3)

In [35]:
x_reshaped.is_contiguous()

True

In [38]:
x.view[3]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [33]:
x.is_contiguous()

True

In [39]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
torch.stack([x,x,x], dim=0)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [41]:
x.squeeze()

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
y = torch.rand(size=(224, 224, 3))

In [43]:
y.shape

torch.Size([224, 224, 3])

In [44]:
y_permuted = y.permute(2, 0, 1)

In [45]:
y_permuted.shape

torch.Size([3, 224, 224])

In [46]:
a = torch.arange(1,10,1)

In [47]:
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a = a.reshape(1,3,3)

In [49]:
a

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [50]:
a[0][0][0]

tensor(1)

In [51]:
a[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [52]:
a[0][0]

tensor([1, 2, 3])

In [54]:
a[:, 0, 0]

tensor([1])

In [58]:
a[:, :, 0]

tensor([[1, 4, 7]])

In [59]:
a[:, 0, :]

tensor([[1, 2, 3]])

In [60]:
a.shape

torch.Size([1, 3, 3])

In [61]:
a.ndim

3

In [69]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor = torch.rand(3,4)

In [70]:
random_tensor

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])